apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-dashboard
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  defaultBackend:
    service:
      name: hello-arc
      port:
        number: 80